export const PROJECT_SCOPE = [
  'Frontend',
  'Backend',
  'Full Stack',
  'Microservices',
  'Monolithic',
  'Serverless',
] as const;

export const TECH_CATEGORIES = [
  {
    id: 'frontend',
    label: 'Frontend',
    options: [
      'Next.js',
      'React',
      'Vue',
      'Angular',
      'Astro',
      'Remix',
      'Nuxt.js',
      'Svelte',
      'SvelteKit',
      'Gatsby',
      'Qwik',
    ] as const,
  },
  {
    id: 'styling',
    label: 'Styling',
    options: [
      'Tailwind CSS',
      'CSS Modules',
      'Styled Components',
      'Sass/SCSS',
      'Bootstrap',
      'Material UI',
      'Chakra UI',
      'Emotion',
      'Less',
      'Shadcn/ui',
      'Radix UI',
      'Framer Motion',
    ] as const,
  },
  {
    id: 'backend',
    label: 'Backend',
    options: [
      '.NET',
      'C#',
      'Node.js',
      'Express',
      'NestJS',
      'Python',
      'Django',
      'FastAPI',
      'Go',
      'Ruby on Rails',
      'Flask',
      'Gin',
      'Java',
      'Spring Boot',
      'PHP',
      'Laravel',
    ] as const,
  },
  {
    id: 'database',
    label: 'Database',
    options: [
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Redis',
      'Firebase',
      'Supabase',
      'Prisma',
      'SQLite',
      'Cassandra',
      'Elasticsearch',
    ] as const,
  },
  {
    id: 'platforms',
    label: 'Platforms',
    options: [
      'Web Application',
      'Mobile App',
      'Desktop App',
      'CLI Tool',
      'API/Backend Service',
      'Browser Extension',
    ],
  },
  {
    id: 'domains',
    label: 'Project Domains',
    options: [
      'E-commerce',
      'SaaS',
      'Social Media',
      'Dashboard/Analytics',
      'CMS/Blogging',
      'AI/ML',
      'DevOps/Infrastructure',
      'Education/Learning',
      'Entertainment',
      'Productivity',
      'Open Source Library',
    ],
  },
  {
    id: 'devops',
    label: 'DevOps & Cloud',
    options: [
      'Docker',
      'Kubernetes',
      'AWS',
      'Azure',
      'Google Cloud',
      'Vercel',
      'Netlify',
      'GitHub Actions',
      'CI/CD',
      'Terraform',
      'Nginx',
      'Linux',
    ] as const,
  },
] as const;
